apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: "{{.Values.serviceLabel}}"
spec:
  destination:
    name: "{{.Values.serviceLabel}}"
  route:
  - labels:
      version: "{{.Values.prodLabel}}"
    weight: {{.Values.prodWeight}}
  - labels:
      version: "{{.Values.canaryLabel}}"
    weight: {{.Values.canaryWeight}}